/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DaoMixVotingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "castVote"
      | "createElection"
      | "electionCount"
      | "elections"
      | "getBallots"
      | "isRegisteredVoter"
      | "registerVoter"
      | "setMixCommitments"
      | "submitTally"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ElectionCreated"
      | "MixCommitmentsSet"
      | "TallySubmitted"
      | "VoteCast"
      | "VoterRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "castVote",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createElection",
    values: [string, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "electionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "elections",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBallots",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegisteredVoter",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerVoter",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMixCommitments",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTally",
    values: [BigNumberish, string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "electionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "elections", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBallots", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegisteredVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMixCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTally",
    data: BytesLike
  ): Result;
}

export namespace ElectionCreatedEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    name: string,
    admin: AddressLike,
    tallyAuthority: AddressLike
  ];
  export type OutputTuple = [
    electionId: bigint,
    name: string,
    admin: string,
    tallyAuthority: string
  ];
  export interface OutputObject {
    electionId: bigint;
    name: string;
    admin: string;
    tallyAuthority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MixCommitmentsSetEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    inputRoot: BytesLike,
    outputRoot: BytesLike
  ];
  export type OutputTuple = [
    electionId: bigint,
    inputRoot: string,
    outputRoot: string
  ];
  export interface OutputObject {
    electionId: bigint;
    inputRoot: string;
    outputRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TallySubmittedEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    resultUri: string,
    resultHash: BytesLike
  ];
  export type OutputTuple = [
    electionId: bigint,
    resultUri: string,
    resultHash: string
  ];
  export interface OutputObject {
    electionId: bigint;
    resultUri: string;
    resultHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    voter: AddressLike,
    index: BigNumberish
  ];
  export type OutputTuple = [electionId: bigint, voter: string, index: bigint];
  export interface OutputObject {
    electionId: bigint;
    voter: string;
    index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoterRegisteredEvent {
  export type InputTuple = [electionId: BigNumberish, voter: AddressLike];
  export type OutputTuple = [electionId: bigint, voter: string];
  export interface OutputObject {
    electionId: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DaoMixVoting extends BaseContract {
  connect(runner?: ContractRunner | null): DaoMixVoting;
  waitForDeployment(): Promise<this>;

  interface: DaoMixVotingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  castVote: TypedContractMethod<
    [electionId: BigNumberish, ballotCipher: BytesLike],
    [void],
    "nonpayable"
  >;

  createElection: TypedContractMethod<
    [
      name: string,
      registrationDeadline: BigNumberish,
      votingDeadline: BigNumberish,
      tallyAuthority: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  electionCount: TypedContractMethod<[], [bigint], "view">;

  elections: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        boolean
      ] & {
        id: bigint;
        name: string;
        registrationDeadline: bigint;
        votingDeadline: bigint;
        admin: string;
        tallyAuthority: string;
        commitmentInputRoot: string;
        commitmentOutputRoot: string;
        finalized: boolean;
      }
    ],
    "view"
  >;

  getBallots: TypedContractMethod<
    [electionId: BigNumberish],
    [string[]],
    "view"
  >;

  isRegisteredVoter: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  registerVoter: TypedContractMethod<
    [electionId: BigNumberish, voter: AddressLike],
    [void],
    "nonpayable"
  >;

  setMixCommitments: TypedContractMethod<
    [electionId: BigNumberish, inputRoot: BytesLike, outputRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  submitTally: TypedContractMethod<
    [electionId: BigNumberish, resultUri: string, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [electionId: BigNumberish, ballotCipher: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createElection"
  ): TypedContractMethod<
    [
      name: string,
      registrationDeadline: BigNumberish,
      votingDeadline: BigNumberish,
      tallyAuthority: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "electionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "elections"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        boolean
      ] & {
        id: bigint;
        name: string;
        registrationDeadline: bigint;
        votingDeadline: bigint;
        admin: string;
        tallyAuthority: string;
        commitmentInputRoot: string;
        commitmentOutputRoot: string;
        finalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBallots"
  ): TypedContractMethod<[electionId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "isRegisteredVoter"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerVoter"
  ): TypedContractMethod<
    [electionId: BigNumberish, voter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMixCommitments"
  ): TypedContractMethod<
    [electionId: BigNumberish, inputRoot: BytesLike, outputRoot: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitTally"
  ): TypedContractMethod<
    [electionId: BigNumberish, resultUri: string, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ElectionCreated"
  ): TypedContractEvent<
    ElectionCreatedEvent.InputTuple,
    ElectionCreatedEvent.OutputTuple,
    ElectionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MixCommitmentsSet"
  ): TypedContractEvent<
    MixCommitmentsSetEvent.InputTuple,
    MixCommitmentsSetEvent.OutputTuple,
    MixCommitmentsSetEvent.OutputObject
  >;
  getEvent(
    key: "TallySubmitted"
  ): TypedContractEvent<
    TallySubmittedEvent.InputTuple,
    TallySubmittedEvent.OutputTuple,
    TallySubmittedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;
  getEvent(
    key: "VoterRegistered"
  ): TypedContractEvent<
    VoterRegisteredEvent.InputTuple,
    VoterRegisteredEvent.OutputTuple,
    VoterRegisteredEvent.OutputObject
  >;

  filters: {
    "ElectionCreated(uint256,string,address,address)": TypedContractEvent<
      ElectionCreatedEvent.InputTuple,
      ElectionCreatedEvent.OutputTuple,
      ElectionCreatedEvent.OutputObject
    >;
    ElectionCreated: TypedContractEvent<
      ElectionCreatedEvent.InputTuple,
      ElectionCreatedEvent.OutputTuple,
      ElectionCreatedEvent.OutputObject
    >;

    "MixCommitmentsSet(uint256,bytes32,bytes32)": TypedContractEvent<
      MixCommitmentsSetEvent.InputTuple,
      MixCommitmentsSetEvent.OutputTuple,
      MixCommitmentsSetEvent.OutputObject
    >;
    MixCommitmentsSet: TypedContractEvent<
      MixCommitmentsSetEvent.InputTuple,
      MixCommitmentsSetEvent.OutputTuple,
      MixCommitmentsSetEvent.OutputObject
    >;

    "TallySubmitted(uint256,string,bytes32)": TypedContractEvent<
      TallySubmittedEvent.InputTuple,
      TallySubmittedEvent.OutputTuple,
      TallySubmittedEvent.OutputObject
    >;
    TallySubmitted: TypedContractEvent<
      TallySubmittedEvent.InputTuple,
      TallySubmittedEvent.OutputTuple,
      TallySubmittedEvent.OutputObject
    >;

    "VoteCast(uint256,address,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;

    "VoterRegistered(uint256,address)": TypedContractEvent<
      VoterRegisteredEvent.InputTuple,
      VoterRegisteredEvent.OutputTuple,
      VoterRegisteredEvent.OutputObject
    >;
    VoterRegistered: TypedContractEvent<
      VoterRegisteredEvent.InputTuple,
      VoterRegisteredEvent.OutputTuple,
      VoterRegisteredEvent.OutputObject
    >;
  };
}
